# Generated by Django 4.1.1 on 2022-09-07 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('establish_year', models.IntegerField()),
                ('founder', models.CharField(max_length=200)),
                ('ceo', models.CharField(max_length=200)),
                ('register_date', models.DateField(auto_now_add=True)),
                ('type', models.CharField(choices=[('Domestic', 'Domestic'), ('International', 'International')], max_length=200)),
                ('sys_type', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=15)),
                ('project_name', models.CharField(max_length=100, verbose_name='Project Name')),
                ('system_parameter_one', models.CharField(max_length=100)),
                ('system_parameter_two', models.CharField(max_length=100)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
