# Generated by Django 4.1.1 on 2022-09-07 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='username',
        ),
    ]
